GPUID: 0
WORKERS: 0
PRINT_FREQ: 10
SAVE_FREQ: 10
PIN_MEMORY: False
OUTPUT_DIR: 'output' # 日志输出路径

DATASET:
  NAME: cat_dog_clc
  IMG_H: 224
  IMG_W: 224
  ROOT: "./datasets" # 数据集路径
  TRAIN_TXT: "./datasets/train.txt"
  TEST_TXT: "./datasets/test.txt"
  STD: 0.193
  MEAN: 0.588

TRAIN:
  BATCH_SIZE_PER_GPU: 32
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: # 从头开始训练
    IS_RESUME: False
    FILE: ''
  OPTIMIZER: 'adam'
  LR: 0.0001 #学习率
  WD: 0.0 #权值衰减
  LR_STEP: [60, 80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:
  FINETUNE: # 微调模型路径
    IS_FINETUNE: false
    FINETUNE_CHECKPOINIT: 'output/checkpoints/mixed_second_finetune_acc_97P7.pth'
    FREEZE: true

TEST:
  BATCH_SIZE_PER_GPU: 16
  SHUFFLE: True  # for random test rather than test on the whole validation set
  NUM_TEST_BATCH: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: mv2
  NUM_CLASSES: 2 # 类别数量

